apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fx5ga9h1o-go 
  janus-idp.io/tekton: fx5ga9h1o-go
  backstage.io/kubernetes-id: fx5ga9h1o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fx5ga9h1o-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  